groupName: acme.balzanel.li

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

deployment:
  secretName: njalla-credentials

apiPriorityAndFairness: false

image:
  repository: ghcr.io/nberlee/cert-manager-webhook-njalla
  tag: v0.2.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
